### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by thatsIch** [Deconimus/JarShrink#3]
You are calling `jdeps` from a `ProcessBuilder` but it does not use the extension-mapping like the console does. With windows you need to add `.exe` to call it from `ProcessBuilder`

You have to do something like this to call it on all runtimes:

https://github.com/shannah/jdeploy/commit/71da650dad1b04c44d7f9f5242439f935c680c09

**Comment by thatsIch** [comment]
I fixed this by something like this. If you have `java` on the path, you also have `jdeps` on the path. No need to fiddle around with the paths. Unless you really want the latest `jdeps`.

	private static boolean isWindows() {
        	return System.getProperty("os.name").toLowerCase().contains("win");
	}
	
	private static String findJdepsLocation() {
		return isWindows() ? "jdeps.exe" : "jdeps";
	}

**Comment by Deconimus** [comment]
I'm also running Windows and strangely I didn't encounter this issue. I'll add your proposed solution though, thank you for the hint.

Regarding ```jdeps```, it isn't necessarily located in your path, if you have both a ```JDK``` and a seperate ```JRE``` installed on your machine and your program is for whatever reason running from the ```JRE```. Since weird installation problems regarding the ```Java Runtime``` are pretty common I wanted to reduce the chance of error there. Ensuring to use the latest version is also a neat bonus I guess.

Edit: Should be fixed now in the latest release, let me know if it works for you.

**Comment by thatsIch** [comment]
You should probably write integration tests with that. AppVeyor is a windows only environment whereas most other are unix (like Travis). I am bummed how it is working for you from the commandline though. I have yet to test the latest version.

**Comment by Deconimus** [comment]
From my personal experience you usually don't need to specify file extensions when running executables on windows. Just like running ```cmd``` is sufficient and you don't need to run ```cmd.exe```.

**Comment by thatsIch** [comment]
yes, if you run it in a cli environment. Do you run it from git bash? or cygwin? Or just from eclipse?

btw it does not work for me. `/` vs `\` in the path

€: aka `File.seperator`

**Comment by Gombat** [comment]
I just tried the v1.0b and it runs using the windows cmd with following call:
`java -jar jarShrink.jar "test.jar" -out "shrunken.jar"`
I'm running Windows 7 and got java 1.8 installed.

**Comment by Deconimus** [comment]
@thatsIch 
I'm running from eclipse and cmd.
Seems like it's not a windows but rather a git bash/cygwin issue then.
I've just switched to using File.separator as you've suggested.

**Comment by thatsIch** [comment]
Thanks, this fixed this issue for me. The next is, that I have not installed the JRE with my JDK. It tries to enforce 

    E:\Work\Programming\Java\JDK 8u91 x64\jre\bin\jdeps.exe

instead of 

    > where jdeps
    E:\Work\Programming\Java\JDK 8u91 x64\bin\jdeps.exe

notice the `\jre\`. I guess you need  to check first if the jdeps.exe actually exists and choose fallbacks?

**Comment by Deconimus** [comment]
Oh, I simply forgot to down enforce lower-case strings when doing the name checks. Also I haven't encountered this specific naming convention your Java installation has.

But yeah I've also added checks whether the file is actually present, good idea.

**Comment by thatsIch** [comment]
It is not :D 
well I choose the installation folder myself and checked off the `JRE`. This is possible with the JDK installer. Though this should not matter since you go over `JAVA_HOME`.

**Comment by thatsIch** [comment]
Does work now. Cheers
