### ISSUE TITLE
NPE on 1.0e 

### ISSUE THREAD

**Issue by thatsIch** [Deconimus/JarShrink#7]
https://ci.appveyor.com/project/thatsIch/sublime-rainmeter-image-smoother/build/1.0.13#L107

running it on 1.0c was fine

https://ci.appveyor.com/project/thatsIch/sublime-rainmeter-image-smoother/build/1.0.18

the download links are in the beginning ~l16

**Comment by Deconimus** [comment]
Oh, that was actually fixed in the most recent revision. Forgot to update the release accordingly.
